CREATE OR REPLACE PROCEDURE CT_CUSTOMER IS
v_tabcnt Number;
BEGIN
Select count (*) INTO v_tabcnt
FROM ALL_TABLES
WHERE TABLE_NAME = 'CUSTOMER' and Owner = User;

if v_tabcnt = 0 then

EXECUTE IMMEDIATE '
CREATE TABLE CUSTOMER 
(
  CUSTOMER_ID INT PRIMARY KEY
, FIRST_NAME VARCHAR2(20) 
, CREDIT DECIMAL(10,2) 
)';
COMMIT;

end if;
